#!/bin/bash
touch 0-puts_recursion.c 1-print_rev_recursion.c 2-strlen_recursion.c 3-factorial.c 4-pow_recursion.c 5-sqrt_recursion.c 6-is_prime_number.c 100-is_palindrome 101-wildcmp.c main.h 
echo "This folder deals with recursion in c" > README.md
